-- Phase 20: Supermarket POS (separate from food catalog)
ALTER TYPE "ChargeType" ADD VALUE IF NOT EXISTS 'SUPERMARKET';
ALTER TABLE "charges" ADD COLUMN IF NOT EXISTS "source_type" TEXT;
ALTER TABLE "charges" ADD COLUMN IF NOT EXISTS "source_id" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "charges_source_type_source_id_key" ON "charges"("source_type", "source_id");

CREATE TYPE "PosStockMovementType" AS ENUM ('RECEIVE','ADJUST_IN','ADJUST_OUT','SALE','REFUND_RESTOCK','DAMAGE','LOSS','EXPIRED','COUNT_ADJUST');
CREATE TYPE "PosShiftStatus" AS ENUM ('OPEN','CLOSED','APPROVED');
CREATE TYPE "PosCashMovementType" AS ENUM ('IN','OUT');
CREATE TYPE "PosSaleStatus" AS ENUM ('COMPLETED','CANCELLED','PARTIALLY_REFUNDED','REFUNDED');
CREATE TYPE "PosPaymentMethod" AS ENUM ('CASH','PROMPTPAY','TRANSFER','ROOM_CHARGE','TOUR_CHARGE');
CREATE TYPE "PosHoldStatus" AS ENUM ('OPEN','RESUMED','CANCELLED');
CREATE TYPE "PosAccountingEntryType" AS ENUM ('CASH_REVENUE','PROMPTPAY_REVENUE','TRANSFER_REVENUE','ROOM_RECEIVABLE','TOUR_RECEIVABLE','DISCOUNT','REFUND','NET_SALES','COGS','GROSS_PROFIT','CASH_OVER_SHORT');

CREATE TABLE "pos_categories" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "name" TEXT NOT NULL UNIQUE, "sort_order" INTEGER NOT NULL DEFAULT 0, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_products" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "sku" TEXT NOT NULL UNIQUE, "barcode" TEXT UNIQUE, "name" TEXT NOT NULL, "category_id" UUID NOT NULL REFERENCES "pos_categories"("id"), "unit" TEXT NOT NULL DEFAULT 'ชิ้น', "cost_price" DECIMAL(12,2) NOT NULL, "sell_price" DECIMAL(12,2) NOT NULL, "quantity_on_hand" DECIMAL(12,3) NOT NULL DEFAULT 0, "low_stock_threshold" DECIMAL(12,3) NOT NULL DEFAULT 0, "image_url" TEXT, "is_active" BOOLEAN NOT NULL DEFAULT true, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_shifts" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "status" "PosShiftStatus" NOT NULL DEFAULT 'OPEN', "opening_float" DECIMAL(12,2) NOT NULL, "closing_cash_counted" DECIMAL(12,2), "expected_cash" DECIMAL(12,2), "cash_variance" DECIMAL(12,2), "opened_by_id" UUID NOT NULL REFERENCES "employees"("id"), "closed_by_id" UUID REFERENCES "employees"("id"), "approved_by_id" UUID REFERENCES "employees"("id"), "opened_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "closed_at" TIMESTAMPTZ, "approved_at" TIMESTAMPTZ, "note" TEXT, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_sales" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "receipt_number" TEXT NOT NULL UNIQUE, "idempotency_key" TEXT NOT NULL UNIQUE, "status" "PosSaleStatus" NOT NULL DEFAULT 'COMPLETED', "shift_id" UUID NOT NULL REFERENCES "pos_shifts"("id"), "sold_by_id" UUID NOT NULL REFERENCES "employees"("id"), "voided_by_id" UUID REFERENCES "employees"("id"), "booking_id" UUID REFERENCES "bookings"("id") ON DELETE SET NULL, "subtotal" DECIMAL(12,2) NOT NULL, "item_discount_total" DECIMAL(12,2) NOT NULL DEFAULT 0, "bill_discount" DECIMAL(12,2) NOT NULL DEFAULT 0, "net_total" DECIMAL(12,2) NOT NULL, "cost_total" DECIMAL(12,2) NOT NULL DEFAULT 0, "cash_received" DECIMAL(12,2), "change_given" DECIMAL(12,2), "note" TEXT, "void_reason" TEXT, "sold_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "voided_at" TIMESTAMPTZ, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_sale_items" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "sale_id" UUID NOT NULL REFERENCES "pos_sales"("id") ON DELETE CASCADE, "product_id" UUID NOT NULL REFERENCES "pos_products"("id"), "product_name" TEXT NOT NULL, "sku" TEXT NOT NULL, "quantity" DECIMAL(12,3) NOT NULL, "unit_price" DECIMAL(12,2) NOT NULL, "cost_price" DECIMAL(12,2) NOT NULL, "discount" DECIMAL(12,2) NOT NULL DEFAULT 0, "line_total" DECIMAL(12,2) NOT NULL);
CREATE TABLE "pos_payments" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "sale_id" UUID NOT NULL REFERENCES "pos_sales"("id") ON DELETE CASCADE, "method" "PosPaymentMethod" NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "reference" TEXT, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_stock_movements" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "product_id" UUID NOT NULL REFERENCES "pos_products"("id"), "type" "PosStockMovementType" NOT NULL, "quantity_delta" DECIMAL(12,3) NOT NULL, "quantity_before" DECIMAL(12,3) NOT NULL, "quantity_after" DECIMAL(12,3) NOT NULL, "document_number" TEXT, "reason" TEXT, "reference_type" TEXT, "reference_id" TEXT, "actor_employee_id" UUID NOT NULL REFERENCES "employees"("id"), "occurred_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_stock_counts" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "document_number" TEXT NOT NULL UNIQUE, "note" TEXT, "counted_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "actor_employee_id" UUID NOT NULL REFERENCES "employees"("id"), "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_stock_count_items" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "count_id" UUID NOT NULL REFERENCES "pos_stock_counts"("id") ON DELETE CASCADE, "product_id" UUID NOT NULL REFERENCES "pos_products"("id"), "system_quantity" DECIMAL(12,3) NOT NULL, "counted_quantity" DECIMAL(12,3) NOT NULL, "variance" DECIMAL(12,3) NOT NULL, UNIQUE ("count_id","product_id"));
CREATE TABLE "pos_cash_movements" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "shift_id" UUID NOT NULL REFERENCES "pos_shifts"("id") ON DELETE CASCADE, "type" "PosCashMovementType" NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "reason" TEXT NOT NULL, "actor_employee_id" UUID NOT NULL REFERENCES "employees"("id"), "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_holds" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "hold_number" TEXT NOT NULL UNIQUE, "status" "PosHoldStatus" NOT NULL DEFAULT 'OPEN', "shift_id" UUID, "held_by_id" UUID NOT NULL REFERENCES "employees"("id"), "bill_discount" DECIMAL(12,2) NOT NULL DEFAULT 0, "note" TEXT, "payload" JSONB NOT NULL, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "resumed_at" TIMESTAMPTZ);
CREATE TABLE "pos_hold_items" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "hold_id" UUID NOT NULL REFERENCES "pos_holds"("id") ON DELETE CASCADE, "product_id" UUID NOT NULL REFERENCES "pos_products"("id"), "quantity" DECIMAL(12,3) NOT NULL, "unit_price" DECIMAL(12,2) NOT NULL, "discount" DECIMAL(12,2) NOT NULL DEFAULT 0);
CREATE TABLE "pos_refunds" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "refund_number" TEXT NOT NULL UNIQUE, "sale_id" UUID NOT NULL REFERENCES "pos_sales"("id"), "reason" TEXT NOT NULL, "restock" BOOLEAN NOT NULL DEFAULT true, "refund_total" DECIMAL(12,2) NOT NULL, "refund_method" "PosPaymentMethod" NOT NULL, "actor_employee_id" UUID NOT NULL REFERENCES "employees"("id"), "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_refund_items" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "refund_id" UUID NOT NULL REFERENCES "pos_refunds"("id") ON DELETE CASCADE, "sale_item_id" UUID NOT NULL REFERENCES "pos_sale_items"("id"), "product_id" UUID NOT NULL REFERENCES "pos_products"("id"), "quantity" DECIMAL(12,3) NOT NULL, "amount" DECIMAL(12,2) NOT NULL);
CREATE TABLE "pos_settings" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "key" TEXT NOT NULL UNIQUE, "value" JSONB NOT NULL, "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_accounting_entries" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "entry_type" "PosAccountingEntryType" NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "occurred_at" TIMESTAMPTZ NOT NULL, "reference_type" TEXT NOT NULL, "reference_id" TEXT NOT NULL, "sale_id" UUID REFERENCES "pos_sales"("id") ON DELETE SET NULL, "description" TEXT NOT NULL, "idempotency_key" TEXT NOT NULL UNIQUE, "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "pos_receipt_sequences" ("id" UUID PRIMARY KEY DEFAULT gen_random_uuid(), "prefix" TEXT NOT NULL UNIQUE, "last_value" INTEGER NOT NULL DEFAULT 0, "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT INTO "permissions" ("id","code","description","created_at","updated_at") VALUES
 (gen_random_uuid(),'pos.view','เข้าถึงหน้าขายซูเปอร์มาร์เก็ต',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.sell','บันทึกการขายซูเปอร์มาร์เก็ต',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.discount','ให้ส่วนลดการขาย',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.hold','พักและเรียกบิลขาย',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.cancel','ยกเลิกบิลขาย',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.refund','คืนสินค้าและคืนเงิน',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.shift.open','เปิดกะขาย',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.shift.close','ปิดกะขาย',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.shift.approve','อนุมัติกะขาย',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.product.view','ดูข้อมูลสินค้าซูเปอร์มาร์เก็ต',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.product.manage','จัดการสินค้าและหมวดหมู่ซูเปอร์มาร์เก็ต',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.stock.view','ดูสต๊อกและประวัติสินค้า',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.stock.receive','รับสินค้าเข้าสต๊อก',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.stock.adjust','ปรับยอดสต๊อก',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.stock.count','ตรวจนับสต๊อก',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.report.view','ดูรายงานยอดขายซูเปอร์มาร์เก็ต',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.accounting.post','ส่งรายการขายเข้าบัญชี',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(gen_random_uuid(),'pos.settings.manage','จัดการตั้งค่าระบบขาย',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("code") DO UPDATE SET "description"=EXCLUDED."description","updated_at"=CURRENT_TIMESTAMP;
INSERT INTO "role_permissions" ("role_id","permission_id") SELECT r."id",p."id" FROM "roles" r CROSS JOIN "permissions" p WHERE r."code"='ADMIN' AND p."code" LIKE 'pos.%' ON CONFLICT DO NOTHING;
INSERT INTO "role_permissions" ("role_id","permission_id") SELECT r."id",p."id" FROM "roles" r CROSS JOIN "permissions" p WHERE r."code"='MANAGER' AND p."code" IN ('pos.view','pos.sell','pos.discount','pos.hold','pos.cancel','pos.refund','pos.shift.open','pos.shift.close','pos.shift.approve','pos.product.view','pos.product.manage','pos.stock.view','pos.stock.receive','pos.stock.adjust','pos.stock.count','pos.report.view','pos.accounting.post','pos.settings.manage') ON CONFLICT DO NOTHING;
INSERT INTO "role_permissions" ("role_id","permission_id") SELECT r."id",p."id" FROM "roles" r CROSS JOIN "permissions" p WHERE r."code"='RECEPTION' AND p."code" IN ('pos.view','pos.sell','pos.hold','pos.shift.open','pos.shift.close','pos.product.view','pos.stock.view') ON CONFLICT DO NOTHING;
INSERT INTO "role_permissions" ("role_id","permission_id") SELECT r."id",p."id" FROM "roles" r CROSS JOIN "permissions" p WHERE r."code"='ACCOUNTING' AND p."code" IN ('pos.view','pos.report.view','pos.accounting.post') ON CONFLICT DO NOTHING;
