"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

type Report = { billCount: number; grossSales: string | number; refunds: string | number; netSales: string | number; cost: string | number; grossProfit: string | number; paymentTotals: Record<string, string | number>; lowStock: Array<{ name: string; quantityOnHand: string | number }> };
function dateInput(date: Date) { return date.toISOString().slice(0, 10); }
function money(value: string | number) { return Number(value).toLocaleString("th-TH", { style: "currency", currency: "THB" }); }
async function getReport(from: string, to: string) { const response = await fetch(`/api/pos/reports?from=${encodeURIComponent(`${from}T00:00:00.000Z`)}&to=${encodeURIComponent(`${to}T23:59:59.999Z`)}`, { cache: "no-store" }); if (!response.ok) throw new Error("โหลดรายงานไม่สำเร็จ"); return response.json() as Promise<Report>; }
export function PosReportsBoard() {
  const [from, setFrom] = useState(() => dateInput(new Date()));
  const [to, setTo] = useState(() => dateInput(new Date()));
  const [report, setReport] = useState<Report | null>(null);
  const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { setReport(await getReport(from, to)); } catch (error) { setMessage(error instanceof Error ? error.message : "โหลดรายงานไม่สำเร็จ"); } }, [from, to]);
  useEffect(() => { void load(); }, [load]);
  function exportCsv() { if (!report) return; const rows = [["รายการ", "จำนวนเงิน"], ["จำนวนบิล", String(report.billCount)], ["ยอดขายสุทธิ", String(report.netSales)], ["ต้นทุน", String(report.cost)], ["กำไรขั้นต้น", String(report.grossProfit)], ...Object.entries(report.paymentTotals)]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll("\"", "\"\"")}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8" })); link.download = `pos-report-${from}-${to}.csv`; link.click(); URL.revokeObjectURL(link.href); }
  return <div className="space-y-4">{message && <p className="rounded-2xl bg-destructive/10 p-3 text-sm text-destructive">{message}</p>}<section className="flex flex-wrap items-end gap-3 rounded-3xl border border-border bg-surface p-4 shadow-sm"><label className="text-sm">ตั้งแต่<input type="date" value={from} onChange={(event) => setFrom(event.target.value)} className="mt-1 block rounded-xl border border-border bg-background px-3 py-2" /></label><label className="text-sm">ถึง<input type="date" value={to} onChange={(event) => setTo(event.target.value)} className="mt-1 block rounded-xl border border-border bg-background px-3 py-2" /></label><button onClick={exportCsv} className="rounded-xl border border-border px-4 py-2">ส่งออก CSV</button><Link href="/dashboard" className="rounded-xl border border-border px-4 py-2">ดูบัญชี/แดชบอร์ด</Link></section>{report && <><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[{ label: "ยอดขายสุทธิ", value: money(report.netSales) }, { label: "จำนวนบิล", value: report.billCount.toLocaleString("th-TH") }, { label: "ต้นทุน", value: money(report.cost) }, { label: "กำไรขั้นต้น", value: money(report.grossProfit) }].map((item) => <section key={item.label} className="rounded-2xl border border-border bg-surface p-4 shadow-sm"><p className="text-sm text-muted-foreground">{item.label}</p><p className="mt-2 text-2xl font-semibold">{item.value}</p></section>)}</div><section className="rounded-3xl border border-border bg-surface p-5 shadow-sm"><h2 className="font-semibold">ยอดชำระตามช่องทาง</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{Object.entries(report.paymentTotals).map(([key, value]) => <div key={key} className="rounded-2xl bg-muted p-3"><p className="text-xs text-muted-foreground">{key}</p><p className="mt-1 font-semibold">{money(value)}</p></div>)}</div><h2 className="mt-5 font-semibold">สินค้าใกล้หมด</h2><ul className="mt-2 text-sm">{report.lowStock.map((item) => <li key={item.name}>{item.name} · เหลือ {item.quantityOnHand}</li>)}</ul></section></>}</div>;
}
