"use client";

import { useCallback, useEffect, useState } from "react";

type Settings = { allowNegativeStock: boolean; receiptPrefix: string; maxRefundDays: number; defaultLowStock: number; storeName: string };
async function api<T>(url: string, options?: RequestInit) { const response = await fetch(url, { cache: "no-store", ...options, headers: { "Content-Type": "application/json", ...options?.headers } }); if (!response.ok) throw new Error(((await response.json().catch(() => null)) as { message?: string } | null)?.message ?? "บันทึกไม่สำเร็จ"); return response.json() as Promise<T>; }
export function PosSettingsBoard() {
  const [settings, setSettings] = useState<Settings | null>(null);
  const [message, setMessage] = useState("");
  const load = useCallback(async () => { try { setSettings(await api<Settings>("/api/pos/settings")); } catch (error) { setMessage(error instanceof Error ? error.message : "โหลดการตั้งค่าไม่สำเร็จ"); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function save() { if (!settings) return; try { await api("/api/pos/settings", { method: "PATCH", body: JSON.stringify(settings) }); setMessage("บันทึกการตั้งค่าแล้ว"); } catch (error) { setMessage(error instanceof Error ? error.message : "บันทึกการตั้งค่าไม่สำเร็จ"); } }
  if (!settings) return <p className="rounded-3xl border border-border bg-surface p-8 text-center text-muted-foreground">กำลังโหลดการตั้งค่า...</p>;
  return <section className="max-w-2xl rounded-3xl border border-border bg-surface p-5 shadow-sm">{message && <p className="mb-4 rounded-xl bg-primary/10 p-3 text-sm">{message}</p>}<h2 className="font-semibold">การตั้งค่า POS</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm">ชื่อร้าน<input value={settings.storeName} onChange={(event) => setSettings({ ...settings, storeName: event.target.value })} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2" /></label><label className="text-sm">คำนำหน้าใบเสร็จ<input value={settings.receiptPrefix} onChange={(event) => setSettings({ ...settings, receiptPrefix: event.target.value })} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2" /></label><label className="text-sm">วันคืนสินค้าสูงสุด<input type="number" value={settings.maxRefundDays} onChange={(event) => setSettings({ ...settings, maxRefundDays: Number(event.target.value) })} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2" /></label><label className="text-sm">จุดแจ้งเตือนสต๊อกเริ่มต้น<input type="number" value={settings.defaultLowStock} onChange={(event) => setSettings({ ...settings, defaultLowStock: Number(event.target.value) })} className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2" /></label></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.allowNegativeStock} onChange={(event) => setSettings({ ...settings, allowNegativeStock: event.target.checked })} /> อนุญาตให้สต๊อกติดลบ</label><button onClick={() => void save()} className="mt-5 rounded-xl bg-primary px-4 py-2 text-primary-foreground">บันทึกการตั้งค่า</button></section>;
}
