import type { Metadata } from "next";
import "../styles/globals.css";
import theme from "@/theme/theme";
import { ThemeProvider } from "@mui/material/styles";
import MainLayoutClient from "@/components/layout/MainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <MainLayoutClient>
            {children}
          </MainLayoutClient>
        </ThemeProvider>
      </body>
    </html>
  );
}
