"use client";
import { CircleCheck, ShipWheel } from "lucide-react";
import { useEffect, useState } from "react";

interface Raft { id: string; number: string; name: string; capacity: number; basePrice: number; booked: boolean }
export default function RaftSelect({ selectedRaftIds, onChange, checkIn, checkOut }: { selectedRaftIds: string[]; onChange: (ids: string[]) => void; checkIn: string; checkOut: string }) {
  const [rafts, setRafts] = useState<Raft[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const load = async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/rafts?checkIn=${encodeURIComponent(checkIn)}&checkOut=${encodeURIComponent(checkOut)}`, { cache: "no-store" }); const data = await response.json() as Raft[] | { message: string }; if (!response.ok || !Array.isArray(data)) throw new Error("message" in data ? data.message : "โหลดแพไม่สำเร็จ"); setRafts(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "โหลดแพไม่สำเร็จ"); } finally { setLoading(false); } }; void load(); }, [checkIn, checkOut]);
  const toggle = (id: string) => onChange(selectedRaftIds.includes(id) ? selectedRaftIds.filter((raftId) => raftId !== id) : [...selectedRaftIds, id]);
  return <fieldset className="rounded-2xl border border-slate-200 p-4"><legend className="px-2 text-sm font-medium">เลือกแพ</legend>{loading ? <p className="text-sm text-slate-500">กำลังตรวจสอบแพว่าง...</p> : error ? <p className="text-sm text-red-600">{error}</p> : <div className="grid gap-2 sm:grid-cols-2">{rafts.map((raft) => { const selected = selectedRaftIds.includes(raft.id); return <button type="button" key={raft.id} disabled={raft.booked} onClick={() => toggle(raft.id)} className={`flex items-center justify-between rounded-xl border p-3 text-left ${raft.booked ? "cursor-not-allowed border-red-200 bg-red-50 text-red-500" : selected ? "border-emerald-300 bg-emerald-50 text-emerald-700" : "border-slate-200 hover:border-indigo-300"}`}><span className="flex items-center gap-3">{selected ? <CircleCheck size={22} /> : <ShipWheel size={22} />}<span><span className="block font-medium">{raft.name}</span><span className="text-xs">{raft.capacity} คน · ฿{raft.basePrice.toLocaleString()}</span></span></span><span className="text-xs">{raft.booked ? "ไม่ว่าง" : selected ? "เลือกแล้ว" : "ว่าง"}</span></button>; })}</div>}<p className="mt-3 text-xs text-slate-500">เลือกแล้ว {selectedRaftIds.length} แพ · <span className="text-red-500">สีแดง = ไม่ว่าง</span></p></fieldset>;
}
