"use client";
import { useEffect, useState } from "react";
import RoomIconSelect from "./RoomIconSlect";

interface Room { id: string | number; number?: string; roomNo?: number; booked?: boolean; zone?: { id: string; name: string }; roomType?: { name: string; bedType?: string | null } }
const fallbackRooms: Room[] = Array.from({ length: 10 }, (_, index) => ({ id: index + 1, roomNo: 101 + index, booked: index === 2 }));
export default function ZoneRoomSelect({ selectedRoomIds = [], onChange, checkIn, checkOut }: { selectedRoomIds?: string[]; onChange?: (roomIds: string[]) => void; checkIn?: string; checkOut?: string }) {
  const [rooms, setRooms] = useState<Room[]>(fallbackRooms); const [zone, setZone] = useState("all"); const [loading, setLoading] = useState(false);
  useEffect(() => { const load = async () => { try { setLoading(true); const query = checkIn && checkOut ? `?checkIn=${encodeURIComponent(checkIn)}&checkOut=${encodeURIComponent(checkOut)}` : ""; const response = await fetch(`/api/rooms${query}`, { cache: "no-store" }); if (!response.ok) throw new Error(); const data = await response.json() as Room[]; if (data.length) setRooms(data); } catch { /* ใช้ข้อมูลสำรอง */ } finally { setLoading(false); } }; void load(); }, [checkIn, checkOut]);
  const zones = Array.from(new Map(rooms.filter((room) => room.zone).map((room) => [room.zone!.id, room.zone!])).values()); const visibleRooms = zone === "all" ? rooms : rooms.filter((room) => room.zone?.id === zone); const toggle = (id: string) => onChange?.(selectedRoomIds.includes(id) ? selectedRoomIds.filter((item) => item !== id) : [...selectedRoomIds, id]);
  return <fieldset className="rounded-2xl border border-slate-200 p-4"><legend className="px-2 text-sm font-medium">เลือกห้องพัก</legend><label className="mb-3 block text-sm text-slate-600">โซน<select value={zone} onChange={(event) => setZone(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5"><option value="all">ทุกโซน</option>{zones.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{loading ? <p className="text-sm text-slate-500">กำลังตรวจสอบห้องว่าง...</p> : <div className="flex flex-wrap gap-2">{visibleRooms.map((room) => { const id = String(room.id); return <RoomIconSelect key={id} roomNo={Number(room.number ?? room.roomNo ?? room.id)} booked={Boolean(room.booked)} selected={selectedRoomIds.includes(id)} onToggle={() => toggle(id)} roomType={room.roomType?.name} bedType={room.roomType?.bedType} />; })}</div>}<div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-500"><span>เลือกแล้ว {selectedRoomIds.length} ห้อง</span><span>🛏 เดี่ยว = เตียงเดี่ยว</span><span>🛏🛏 คู่ = เตียงคู่/คิงไซส์</span><span className="text-red-500">สีแดง = ไม่ว่าง</span><span>ชี้เมาส์เพื่อดูประเภทห้อง</span></div></fieldset>;
}
